### PR TITLE
Bestiary JSON: CR: Typos, Classifications, Standardisation

### PR DESCRIPTION
**Pull request by NightB1ade**
I did a deeper dive in the Core Rulebook, spotted more things:
- Some more typos/data errors
- Added more classifications (based on the ones in the SRD)
- Standardised coding (alphabetical classifications)

I also did it in Atom, which got rid of all the trailing spaces when I saved... xD

### CODE REVIEW

**Comment by NightB1ade** [comment]
I'm working on making a stat block page generator, so will be going through 13 True Ways, and the Bestiaries (comparing them to the SRD), so hopefully will get 13TW checked in a deeper dive too!

**Comment by brehaut** [comment]
This is great work, thank you

**Comment by brehaut** [comment]
> I'm working on making a stat block page generator, so will be going through 13 True Ways, and the Bestiaries (comparing them to the SRD), so hopefully will get 13TW checked in a deeper dive too!

Just thinking outloud, If you are driving your tool of the same dataset, then it probably wouldn't be too hard to make manticore able to link to your app to convert an encounter its generated into an editable encounter in your tool for a GM to further refine

**Comment by NightB1ade** [comment]
I'll clarify that as of current it's mainly a "Monster Stat Block" presenter for easy printing.  

It's not quite the same dataset, I modelled it slightly differently (groupings had priority in my data model) and had to add a whole load of more information from the SRD (which I'm slowly working through whenever I get some free time).

You can find it here:
- https://13th-age.github.io/Monster-Stat-Blocks/
- https://github.com/13th-Age/Monster-Stat-Blocks/tree/main/assets/json

Also...  I'm really a Data Architect, so the bit I'm good at is the JSON/data bit :P  The rest of the web design bit is all pretty basic!

The datasets could be combined in terms of content (main bit that's missing this side is the page numbers, and some of the custom groupings/tags that have been added.  So theoretically we could definitely combine them :O

On a personal level, would happily work together to figure it out :P  Definitely would need some sort of shared dataset though!

To be honest, you might look at my basic webpage and balk and reconsider.  (Easy thought is that you could just pre-populate the webpage's dropdowns, by supplying it in the GET of the index position required, and the page can populate dropdowns if that GET is supplied).

**Pull request merged**
